name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  windows_build:
    name: Windows Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-tags: true
          fetch-depth: 0
      - name: Compile
        run: |
          mkdir build
          cmake -S . -B build -DBUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF -Wno-dev
          cmake --build build --config Release --target package
      - name: 'Upload Windows Installer'
        uses: actions/upload-artifact@v4
        with:
          name: 'Windows Installer'
          path: build/_CPack_Packages/win64/NSIS/*.exe
  mac_intel_build:
    name: MacOS x86_64 Build
    runs-on: macos-latest-large
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-tags: true
          fetch-depth: 0
      - name: Compile
        run: |
          mkdir build
          export CC=$(brew --prefix llvm@18)/bin/clang
          export CXX=$(brew --prefix llvm@18)/bin/clang++
          export CMAKE_C_FLAGS="-arch x86_64"
          export CMAKE_CXX_FLAGS="-arch x86_64"
          cmake -S . -B build -DBUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF -Wno-dev
          cmake --build build --config Release --target package
          mv build/_CPack_Packages/OSX/DragNDrop/*.dmg build/_CPack_Packages/OSX/DragNDrop/AgIsoVirtualTerminal-intel.dmg
      - name: 'Upload OSX Intel Installer'
        uses: actions/upload-artifact@v4
        with:
          name: 'OSX Intel dmg package'
          path: build/_CPack_Packages/OSX/DragNDrop/AgIsoVirtualTerminal-intel.dmg
  mac_arm_build:
    name: MacOS ARM Build
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-tags: true
          fetch-depth: 0
      - name: Compile
        run: |
          mkdir build
          export CC=$(brew --prefix llvm@18)/bin/clang
          export CXX=$(brew --prefix llvm@18)/bin/clang++
          export CMAKE_C_FLAGS="-arch arm64"
          export CMAKE_CXX_FLAGS="-arch arm64"
          cmake -S . -B build -DBUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF -Wno-dev
          cmake --build build --config Release --target package
          mv build/_CPack_Packages/OSX/DragNDrop/*.dmg build/_CPack_Packages/OSX/DragNDrop/AgIsoVirtualTerminal-arm64.dmg
      - name: 'Upload OSX ARM Installer'
        uses: actions/upload-artifact@v4
        with:
          name: 'OSX ARM dmg package'
          path: build/_CPack_Packages/OSX/DragNDrop/AgIsoVirtualTerminal-arm64.dmg
  ubuntu_22_04_build:
    name: Ubuntu 22.04 Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-tags: true
          fetch-depth: 0
      - name: Compile
        run: |
          mkdir build
          sudo apt update
          sudo apt install libasound2-dev libjack-jackd2-dev ladspa-sdk libcurl4-openssl-dev libfreetype6-dev libx11-dev libxcomposite-dev libxcursor-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev libwebkit2gtk-4.0-dev libglu1-mesa-dev mesa-common-dev
          cmake -S . -B build -DBUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF -Wno-dev
          cmake --build build --config Release
          cd build
          cpack -G DEB
      - name: 'Upload Ubuntu 22.04 deb package'
        uses: actions/upload-artifact@v4
        with:
          name: 'Ubuntu 22.04 deb package'
          path: build/_CPack_Packages/Linux/DEB/*.deb
  ubuntu_24_04_build:
    name: Ubuntu 24.04 Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-tags: true
          fetch-depth: 0
      - name: Compile
        run: |
          mkdir build
          sudo apt update
          sudo apt install libasound2-dev libjack-jackd2-dev ladspa-sdk libcurl4-openssl-dev libfreetype-dev libfontconfig1-dev libx11-dev libxcomposite-dev libxcursor-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev libglu1-mesa-dev mesa-common-dev git cmake
          cmake -S . -B build -DBUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF -Wno-dev
          cmake --build build --config Release
          cd build
          cpack -G DEB
      - name: 'Upload Ubuntu 24.04 deb package'
        uses: actions/upload-artifact@v4
        with:
          name: 'Ubuntu 24.04 deb package'
          path: build/_CPack_Packages/Linux/DEB/*.deb
